
name: ANNarchy
channels:
  - conda-forge
  - defaults
dependencies:
  - setuptools
  - numpy
  - cython
  - scipy
  - sympy
  - matplotlib
  - pip:
    - mkdocs-material 
    - mkdocstrings 
    - pymdown-extensions 
    - mknotebooks
    - ANNarchy