site_name: ANNarchy

theme:
  name: material
  logo: _static/logowhite.svg
  favicon: _static/logo.svg

  features:
#     - toc.integrate
     - header.autohide
#    - navigation.tabs
#    - navigation.expand
#    - navigation.sections
  
  palette:
    primary: black
    accent: indigo

  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2021 Julien Vitay, Helge Ülo Dinkelbach, Fred H. Hamker
#repo_url: https://github.com/ANNarchy/ANNarchy
repo_url: https://bitbucket.org/ANNarchy/ANNarchy

plugins:
  - search
  - mkdocstrings
  - mknotebooks:
      execute: false
      write_markdown: false
      binder: false


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Installation: 'Installation.md'
  - 'Manual':
    - 'manual/Structure.md'
    - 'manual/Parser.md'
    - 'manual/RateNeuron.md'
    - 'manual/SpikeNeuron.md'
    - 'manual/RateSynapse.md'
    - 'manual/SpikeSynapse.md'
    - 'manual/Populations.md'
    - 'manual/Projections.md'
    - 'manual/Connector.md'
    - 'manual/Inputs.md'
    - 'manual/Simulation.md'
    - 'manual/Configuration.md'
    - 'manual/NumericalMethods.md'
    - 'manual/Recording.md'
    - 'manual/Saving.md'
    - 'manual/Network.md'
    - 'manual/Hybrid.md'
    - 'manual/StructuralPlasticity.md'
    - 'manual/ConvolutionalNetworks.md'
    - 'manual/Notebooks.ipynb'
    - 'manual/Reporting.md'
    - 'manual/Logging.md'
  - 'API':
    - 'API/ANNarchy.md'
    - 'API/Neuron.md'
    - 'API/SpecificNeuron.md'
    - 'API/Synapse.md'
    - 'API/SpecificSynapse.md'
    - 'API/Population.md'
    - 'API/SpecificPopulation.md'
    - 'API/Projection.md'
    - 'API/SpecificProjection.md'
    - 'API/Dendrite.md'
    - 'API/Monitor.md'
    - 'API/RandomDistribution.md'
    - 'API/Network.md'
    - 'API/IO.md'
    - 'API/Utilities.md'
    - 'API/Hybrid.md'
    - 'API/Convolution.md'
    - 'API/Logging.md'
  - 'Examples':
    - 'example/List.md'
    - Neural Field: 'example/NeuralField.ipynb'
    - Bar Learning: 'example/BarLearning.ipynb'
    - Image: 'example/Image.ipynb'
    - Webcam: 'example/Webcam.ipynb'
    - Multiple networks: 'example/MultipleNetworks.ipynb'
    - Structural plasticity: 'example/StructuralPlasticity.ipynb'
    - Izhikevich: 'example/Izhikevich.ipynb'
    - Gap junctions: 'example/GapJunctions.ipynb'
    - Hodgkin-Huxley: 'example/HodgkinHuxley.ipynb'
    - COBA: 'example/COBA.ipynb'
    - STP: 'example/STP.ipynb'
    - STDP: 'example/SimpleSTDP.ipynb'
    - Ramp: 'example/Ramp.ipynb'
    - Hybrid: 'example/Hybrid.ipynb'
    - Bayesian optimization: 'example/BayesianOptimization.ipynb'
    - Basal Ganglia: 'example/BasalGanglia.ipynb'
  - 'License.md'