---
title: Publications

toc: false
---

Oliver Maith, Helge Ülo Dinkelbach, Javier Baladron, Julien Vitay, and Fred H. Hamker (2022).\
**BOLD monitoring in the neural simulator ANNarchy.**\
*Frontiers in Neuroinformatics 16:790966*\
[doi:10.3389/fninf.2022.790966](https:doi.org/10.3389/fninf.2022.790966)

  
Helge Ülo Dinkelbach, Badr-Eddine Bouhlal, Julien Vitay, and Fred H. Hamker (2022).\
**Auto-selection of an optimal sparse matrix format in the neuro-simulator ANNarchy.**\
*Frontiers in Neuroinformatics 16:877945*\
[doi:10.3389/fninf.2022.877945](https:doi.org/10.3389/fninf.2022.877945)

Helge Ülo Dinkelbach, Julien Vitay, and Fred H. Hamker (2019).\
**Scalable simulation of rate-coded and spiking neural networks on shared memory systems.**\
*2019 Conference on Cognitive Computational Neuroscience, 13-16 September 2019, Berlin, Germany.* \
[doi:10.32470/CCN.2019.1109-0](https:doi.org/10.32470/CCN.2019.1109-0)

Julien Vitay, Helge Ülo Dinkelbach, and Fred H. Hamker (2015).\
**ANNarchy: a code generation approach to neural simulations on parallel hardware.**\
*Frontiers in Neuroinformatics 9:19*\
[doi:10.3389/fninf.2015.00019](https:doi.org/10.3389/fninf.2015.00019)

Helge Ü. Dinkelbach, Julien Vitay, and Fred H. Hamker (2012).\
**Comparison of GPU- and CPU-implementations of mean-firing rate neural networks on parallel hardware.**\
*Network: Computation in Neural Systems 23(4)*\
[doi:10.3109/0954898X.2012.739292](https:doi.org/10.3109/0954898X.2012.739292)