# Binomial { #ANNarchy.core.Random.Binomial }

```python
Binomial(n, p, rng=None)
```

Binomial distribution.

Parameters: n trials and p probability of success where n an integer >= 0 and p is in the interval [0,1].

The returned values are the number of successes over the n trials.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                                                                          | Default    |
|--------|---------------------|--------------------------------------------------------------------------------------|------------|
| n      | int                 | Number of trials.                                                                    | _required_ |
| p      | float               | Probability of success.                                                              | _required_ |
| rng    | np.random.Generator | (optional) random number generator. If left None, `np.random.default_rng()` is used. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [get_values](#ANNarchy.core.Random.Binomial.get_values) | Returns a Numpy array with the given shape. |

### get_values { #ANNarchy.core.Random.Binomial.get_values }

```python
get_values(shape)
```

Returns a Numpy array with the given shape.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description         | Default    |
|--------|--------|---------------------|------------|
| shape  | tuple  | shape of the array. | _required_ |