# Constant { #ANNarchy.core.Constant.Constant }

```python
Constant(name, value, net_id=0)
```

Constant parameter that can be used by all neurons and synapses.

The class `Constant` derives from `float`, so any legal operation on floats (addition, multiplication) can be used, but it returns a float.

If a Neuron/Synapse already defines a parameter with the same name, the constant will not be visible.

The constant can be declared at the global level, usually before the neuron/synapse definition:

```python
tau = ann.Constant('tau', 20)
factor = ann.Constant('factor', 0.1)
real_tau = ann.Constant('real_tau', tau*factor)

neuron = ann.Neuron(
    equations=[
        'real_tau * dr/dt + r = 1.0'
    ]
)

net = ann.Network()
net.create(10, neuron)
net.compile()
```

The value of the constant can be changed anytime with the ``set()`` method. 

```python
tau.set(30.0)
```

If `tau` was defined at the global level, ALL networks using that constant will see the change. If you want the change to impact only one network, you should first retrieve the local `Constant` instance from the network:

```python
tau = net.get_constant('tau')
tau.set(30.0)
```

Assignments will have no effect (e.g. `tau = 10.0` creates a new float and erases the `Constant` object).

The value of constants defined as combination of other constants (`real_tau`) is not updated if the value of these constants changes (changing `tau` with `tau.set(10.0)` will not modify the value of `real_tau`).

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                                      | Default    |
|--------|--------|----------------------------------------------------------------------------------|------------|
| name   | str    | name of the constant (unique), which can be used in equations.                   | _required_ |
| value  | float  | the value of the constant, which must be a float, or a combination of Constants. | _required_ |

## Attributes

| Name | Description |
| --- | --- |
| [name](#ANNarchy.core.Constant.Constant.name) | Name. |
| [value](#ANNarchy.core.Constant.Constant.value) | Value. |

## Methods

| Name | Description |
| --- | --- |
| [set](#ANNarchy.core.Constant.Constant.set) | Changes the value of the constant.  |

### set { #ANNarchy.core.Constant.Constant.set }

```python
set(value)
```

Changes the value of the constant. 

If the constant was declared globally, this impacts all networks. Call `Network.get_constant(name)` if you want to impact a single network.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description   | Default    |
|--------|--------|---------------|------------|
| value  | float  | Value.        | _required_ |