# Dendrite { #ANNarchy.core.Dendrite.Dendrite }

```python
Dendrite(proj, post_rank, idx)
```

Sub-group of a `Projection` for a single post-synaptic neuron.

It can not be created directly, only through a call to ``Projection.dendrite(rank)``:

```python
dendrite = proj.dendrite(6)
```

## Attributes

| Name | Description |
| --- | --- |
| [post_rank](#ANNarchy.core.Dendrite.Dendrite.post_rank) | Rank of the post-synaptic neuron. |
| [proj](#ANNarchy.core.Dendrite.Dendrite.proj) | Parent projection. |
| [size](#ANNarchy.core.Dendrite.Dendrite.size) | Number of synapses reaching the post-synaptic neuron. |
| [pre_ranks](#ANNarchy.core.Dendrite.Dendrite.pre_ranks) | List of ranks of pre-synaptic neurons. |
| [synapses](#ANNarchy.core.Dendrite.Dendrite.synapses) | Iteratively returns the synapses corresponding to this dendrite. |

## Methods

| Name | Description |
| --- | --- |
| [synapse](#ANNarchy.core.Dendrite.Dendrite.synapse) | Returns the synapse coming from the corresponding presynaptic neuron. |
| [set](#ANNarchy.core.Dendrite.Dendrite.set) | Sets the value of a parameter/variable on all synapses in the dendrite. |
| [get](#ANNarchy.core.Dendrite.Dendrite.get) | Returns the value of a parameter/variable. |
| [receptive_field](#ANNarchy.core.Dendrite.Dendrite.receptive_field) | Returns the given variable as a receptive field. |
| [create_synapse](#ANNarchy.core.Dendrite.Dendrite.create_synapse) | Creates a single synapse for this dendrite with the given pre-synaptic neuron. |
| [create_synapses](#ANNarchy.core.Dendrite.Dendrite.create_synapses) | Creates a set of synapses for this dendrite with the given pre-synaptic neurons. |
| [prune_synapse](#ANNarchy.core.Dendrite.Dendrite.prune_synapse) | Removes the synapse with the given pre-synaptic neuron from the dendrite. |
| [prune_synapses](#ANNarchy.core.Dendrite.Dendrite.prune_synapses) | Removes the synapses which belong to the provided pre-synaptic neurons from the dendrite. |

### synapse { #ANNarchy.core.Dendrite.Dendrite.synapse }

```python
synapse(pos)
```

Returns the synapse coming from the corresponding presynaptic neuron.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                                                         | Default    |
|--------|---------------------|---------------------------------------------------------------------|------------|
| pos    | int \| tuple\[int\] | can be either the rank or the coordinates of the presynaptic neuron | _required_ |

### set { #ANNarchy.core.Dendrite.Dendrite.set }

```python
set(value)
```

Sets the value of a parameter/variable on all synapses in the dendrite.

```python
dendrite.set( { 'tau' : 20, 'w'= Uniform(0.0, 1.0) } )
```

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                   | Default    |
|--------|--------|---------------------------------------------------------------|------------|
| value  | dict   | a dictionary containing the parameter/variable names as keys. | _required_ |

### get { #ANNarchy.core.Dendrite.Dendrite.get }

```python
get(name)
```

Returns the value of a parameter/variable.

```python
dendrite.get('w')
```

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                     | Default    |
|--------|--------|---------------------------------|------------|
| name   | str    | name of the parameter/variable. | _required_ |

### receptive_field { #ANNarchy.core.Dendrite.Dendrite.receptive_field }

```python
receptive_field(variable='w', fill=0.0)
```

Returns the given variable as a receptive field.

A numpy array of the same geometry as the pre-synaptic population is returned. 
Non-existing synapses are replaced by zeros (or the value ``fill``).

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type   | Description                                                | Default   |
|----------|--------|------------------------------------------------------------|-----------|
| variable | str    | name of the variable (default = 'w')                       | `'w'`     |
| fill     | float  | value to use when a synapse does not exist (default: 0.0). | `0.0`     |

### create_synapse { #ANNarchy.core.Dendrite.Dendrite.create_synapse }

```python
create_synapse(rank, w=0.0, delay=0)
```

Creates a single synapse for this dendrite with the given pre-synaptic neuron.

The configuration key `'structural_plasticity'` must be set to `True` before `compile()` for this method to work. 

```python
net = ann.Network()
net.config(structural_plasticity=True)
net.compile()

try:
    proj.dendrite(10).create_synapse(rank=20, w=0.1, delay=0.0)
except Exception as e:
    print(e)
```

If the synapse already exists, an error is thrown, so make sure to catch the exception.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                       | Default    |
|--------|--------|-------------------------------------------------------------------|------------|
| rank   | int    | rank of the pre-synaptic neuron                                   | _required_ |
| w      | float  | synaptic weight.                                                  | `0.0`      |
| delay  | float  | synaptic delay in milliseconds that should be a multiple of *dt*. | `0`        |

### create_synapses { #ANNarchy.core.Dendrite.Dendrite.create_synapses }

```python
create_synapses(ranks, weights=None, delays=None)
```

Creates a set of synapses for this dendrite with the given pre-synaptic neurons.

The configuration key `'structural_plasticity'` must be set to `True` before `compile()` for this method to work. 

```python
net = ann.Network()
net.config(structural_plasticity=True)
net.compile()

try:
    proj.dendrite(10).create_synapses(ranks=[20, 30, 40], weights=0.1, delay=0.0)
except Exception as e:
    print(e)
```

If the synapses already exist, an error is thrown, so make sure to catch the exception.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                   | Description                                 | Default    |
|---------|------------------------|---------------------------------------------|------------|
| ranks   | list\[int\]            | list of ranks for the pre-synaptic neurons. | _required_ |
| weights | float \| list\[float\] | list of synaptic weights (default: 0.0).    | `None`     |
| delays  | float \| list\[float\] | list of synaptic delays (default = dt).     | `None`     |

### prune_synapse { #ANNarchy.core.Dendrite.Dendrite.prune_synapse }

```python
prune_synapse(rank)
```

Removes the synapse with the given pre-synaptic neuron from the dendrite.

The configuration key `'structural_plasticity'` must be set to `True` before `compile()` for this method to work. 

```python
net = ann.Network()
net.config(structural_plasticity=True)
net.compile()

try:
    proj.dendrite(10).prune_synapse(rank=20)
except Exception as e:
    print(e)
```

If the synapse does not exist, an error is thrown, so make sure to catch the exception.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                     | Default    |
|--------|--------|---------------------------------|------------|
| rank   | int    | rank of the pre-synaptic neuron | _required_ |

### prune_synapses { #ANNarchy.core.Dendrite.Dendrite.prune_synapses }

```python
prune_synapses(ranks)
```

Removes the synapses which belong to the provided pre-synaptic neurons from the dendrite.

The configuration key `'structural_plasticity'` must be set to `True` before `compile()` for this method to work. 

```python
net = ann.Network()
net.config(structural_plasticity=True)
net.compile()

try:
    proj.dendrite(10).prune_synapses(ranks=[20, 30, 40])
except Exception as e:
    print(e)
```

If the synapses do not exist, an error is thrown, so make sure to catch the exception.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type        | Description                                | Default    |
|--------|-------------|--------------------------------------------|------------|
| ranks  | list\[int\] | list of ranks of the pre-synaptic neurons. | _required_ |