# DiscreteUniform { #ANNarchy.core.Random.DiscreteUniform }

```python
core.Random.DiscreteUniform(self, min, max, seed=None)
```

Discrete uniform distribution between ``min`` and ``max``.

The returned values are integers in the range [min, max].

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                                                                                                                     | Default    |
|--------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| min    | int    | minimum value.                                                                                                                                                  | _required_ |
| max    | int    | maximum value.                                                                                                                                                  | _required_ |
| seed   | int    | (optional) seed for the random generator. If left None, the value set in `ann.setup()` or `Network.set_seed()` is used. If both are None, `time(NULL)` is used. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [get_values](#ANNarchy.core.Random.DiscreteUniform.get_values) | Returns a Numpy array with the given shape. |

### get_values { #ANNarchy.core.Random.DiscreteUniform.get_values }

```python
core.Random.DiscreteUniform.get_values(shape)
```

Returns a Numpy array with the given shape.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description         | Default    |
|--------|--------|---------------------|------------|
| shape  | tuple  | Shape of the array. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description   |
|--------|------------|---------------|
|        | np.ndarray | Array.        |