# EIF_cond_exp_isfa_ista { #ANNarchy.models.Neurons.EIF_cond_exp_isfa_ista }

```python
EIF_cond_exp_isfa_ista(
    v_rest=-70.6,
    cm=0.281,
    tau_m=9.3667,
    tau_refrac=0.1,
    tau_syn_E=5.0,
    tau_syn_I=5.0,
    e_rev_E=0.0,
    e_rev_I=-80.0,
    tau_w=144.0,
    a=4.0,
    b=0.0805,
    i_offset=0.0,
    delta_T=2.0,
    v_thresh=-50.4,
    v_reset=-70.6,
    v_spike=-40.0,
)
```

Exponential integrate-and-fire neuron with spike triggered and sub-threshold adaptation currents (isfa, ista reps.), decaying-exponential post-synaptic conductances.
 
Definition according to:

> Brette R and Gerstner W (2005) Adaptive Exponential Integrate-and-Fire Model as an Effective Description of Neuronal Activity. J Neurophysiol 94:3637-3642

Equivalent code:

```python

EIF_cond_exp_isfa_ista = Neuron(
    parameters = dict(
        v_rest = ann.Parameter(-70.6),
        cm = ann.Parameter(0.281), 
        tau_m = ann.Parameter(9.3667), 
        tau_syn_E = ann.Parameter(5.0),
        tau_syn_I = ann.Parameter(5.0), 
        e_rev_E = ann.Parameter(0.0),
        e_rev_I = ann.Parameter(-80.0),
        tau_w = ann.Parameter(144.0), 
        a = ann.Parameter(4.0),
        b = ann.Parameter(0.0805),
        i_offset = ann.Parameter(0.0),
        delta_T = ann.Parameter(2.0),
        v_thresh = ann.Parameter(-50.4),
        v_reset = ann.Parameter(-70.6),
        v_spike = ann.Parameter(-40.0),
    ), 
    equations = [
        # Input current
        'I = g_exc * (e_rev_E - v) + g_inh * (e_rev_I - v) + i_offset',     
        # Membrane potential     
        ann.Variable('tau_m * dv/dt = (v_rest - v +  delta_T * exp((v-v_thresh)/delta_T)) + tau_m/cm*(I - w)', init=-70.6),     
        # Recovery variable 
        'tau_w * dw/dt = a * (v - v_rest) / 1000.0 - w',       
        # Conductances
        ann.Variable('tau_syn_E * dg_exc/dt = - g_exc', method='exponential'),
        ann.Variable('tau_syn_I * dg_inh/dt = - g_inh', method='exponential'),
    ],
    spike = "v > v_spike",
    reset = """
        v = v_reset
        w += b
    """,
    refractory = 0.1
)
```

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                        | Default   |
|------------|--------|----------------------------------------------------|-----------|
| v_rest     |        | Resting membrane potential (mV)                    | `-70.6`   |
| cm         |        | Capacity of the membrane (nF)                      | `0.281`   |
| tau_m      |        | Membrane time constant (ms)                        | `9.3667`  |
| tau_refrac |        | Duration of refractory period (ms)                 | `0.1`     |
| tau_syn_E  |        | Decay time of excitatory synaptic current (ms)     | `5.0`     |
| tau_syn_I  |        | Decay time of inhibitory synaptic current (ms)     | `5.0`     |
| e_rev_E    |        | Reversal potential for excitatory input (mV)       | `0.0`     |
| e_rev_I    |        | Reversal potential for inhibitory input (mv)       | `-80.0`   |
| tau_w      |        | Time constant of the adaptation variable (ms)      | `144.0`   |
| a          |        | Scaling of the adaptation variable                 | `4.0`     |
| b          |        | Increment on the adaptation variable after a spike | `0.0805`  |
| i_offset   |        | Offset current (nA)                                | `0.0`     |
| delta_T    |        | Speed of the exponential (mV)                      | `2.0`     |
| v_thresh   |        | Spike threshold for the exponential (mV)           | `-50.4`   |
| v_reset    |        | Reset potential after a spike (mV)                 | `-70.6`   |
| v_spike    |        | Spike threshold (mV)                               | `-40.0`   |