# Exponential { #ANNarchy.core.Random.Exponential }

`core.Random.Exponential(self, Lambda, min=None, max=None, seed=None)`

Exponential distribution, according to the density function:

$$P(x | \lambda) = \lambda e^{(-\lambda x )}$$

**Note:** ``Lambda`` is capitalized, otherwise it would be a reserved Python keyword.

## Parameters

| Name     | Type   | Description                                                                                     | Default    |
|----------|--------|-------------------------------------------------------------------------------------------------|------------|
| `Lambda` | float  | rate parameter.                                                                                 | _required_ |
| `min`    | float  | minimum value (default: unlimited).                                                             | `None`     |
| `max`    | float  | maximum value (default: unlimited).                                                             | `None`     |
| `seed`   | int    | (optional) seed for the random generator. If left None, the value set in `ann.setup()` is used. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [get_values](#ANNarchy.core.Random.Exponential.get_values) | Returns a Numpy array with the given shape. |

### get_values { #ANNarchy.core.Random.Exponential.get_values }

`core.Random.Exponential.get_values(shape)`

Returns a Numpy array with the given shape.

#### Parameters

| Name    | Type   | Description         | Default    |
|---------|--------|---------------------|------------|
| `shape` | tuple  | Shape of the array. | _required_ |

#### Returns

| Type       | Description   |
|------------|---------------|
| np.ndarray | Array.        |