# LogNormal { #ANNarchy.core.Random.LogNormal }

```python
LogNormal(self, mu, sigma, min=None, max=None, seed=None)
```

Log-normal distribution.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                                                                                                                     | Default    |
|--------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| mu     | float  | Mean of the distribution.                                                                                                                                       | _required_ |
| sigma  | float  | Standard deviation of the distribution.                                                                                                                         | _required_ |
| min    | float  | Minimum value (default: unlimited).                                                                                                                             | `None`     |
| max    | float  | Maximum value (default: unlimited).                                                                                                                             | `None`     |
| seed   | int    | (optional) seed for the random generator. If left None, the value set in `ann.setup()` or `Network.set_seed()` is used. If both are None, `time(NULL)` is used. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [get_values](#ANNarchy.core.Random.LogNormal.get_values) | Returns a Numpy array with the given shape. |

### get_values { #ANNarchy.core.Random.LogNormal.get_values }

```python
get_values(shape)
```

Returns a Numpy array with the given shape.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description         | Default    |
|--------|--------|---------------------|------------|
| shape  | tuple  | shape of the array. | _required_ |