# Neuron { #ANNarchy.core.Neuron.Neuron }

```python
Neuron(
    parameters='',
    equations='',
    spike=None,
    axon_spike=None,
    reset=None,
    axon_reset=None,
    refractory=None,
    functions=None,
    name='',
    description='',
    extra_values={},
)
```

Base class to define a neuron model.

Neurons are rate-coded by default (in which case they must define the variable `r`). `parameters` expects a dictionary of parameter values, `equations` expects a list of variables. 

Spiking neurons must define the `spike` condition (and usually also `reset`). They do not need to define `r`. 

```python
LIF = ann.Neuron(
    parameters = dict(
        tau = 10.0
    ),
    equations = [
        "tau * dv/dt + v = g_exc",
    ],
    spike = "v > 30.0",
    reset = "v = 0.0",
    refractory = 5.0,
    name = "LIF",
    description = "Leaky Integrate-and-Fire spiking neuron with time constant $\tau$." 
)
```

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type        | Description                                                                                                                                                                        | Default   |
|-------------|-------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| parameters  | str \| dict | parameters of the neuron and their initial value.                                                                                                                                  | `''`      |
| equations   | str \| list | equations defining the temporal evolution of variables.                                                                                                                            | `''`      |
| functions   | str         | additional functions used in the variables' equations.                                                                                                                             | `None`    |
| spike       | str         | condition to emit a spike (only for spiking neurons).                                                                                                                              | `None`    |
| axon_spike  | str         | condition to emit an axonal spike (only for spiking neurons and optional). The axonal spike can appear additional to the spike and is independent from refractoriness of a neuron. | `None`    |
| reset       | str \| list | changes to the variables after a spike (only for spiking neurons).                                                                                                                 | `None`    |
| axon_reset  | str \| list | changes to the variables after an axonal spike (only for spiking neurons).                                                                                                         | `None`    |
| refractory  | str         | refractory period of a neuron after a spike (only for spiking neurons).                                                                                                            | `None`    |
| name        | str         | name of the neuron type (used for reporting only).                                                                                                                                 | `''`      |
| description | str         | short description of the neuron type (used for reporting).                                                                                                                         | `''`      |