# Normal { #ANNarchy.core.Random.Normal }

```python
Normal(mu, sigma, min=None, max=None, rng=None)
```

Normal distribution.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                                                                                                               | Default    |
|--------|---------------------|---------------------------------------------------------------------------------------------------------------------------|------------|
| mu     | float               | Mean of the distribution.                                                                                                 | _required_ |
| sigma  | float               | Standard deviation of the distribution.                                                                                   | _required_ |
| min    | float               | Minimum value (default: unlimited).                                                                                       | `None`     |
| max    | float               | Maximum value (default: unlimited).                                                                                       | `None`     |
| rng    | np.random.Generator | (optional) random number generator. If left None, a newly created instance provided by `np.random.default_rng()` is used. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [get_values](#ANNarchy.core.Random.Normal.get_values) | Returns a Numpy array with the given shape. |

### get_values { #ANNarchy.core.Random.Normal.get_values }

```python
get_values(shape)
```

Returns a Numpy array with the given shape.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description         | Default    |
|--------|--------|---------------------|------------|
| shape  | tuple  | shape of the array. | _required_ |