# projections { #ANNarchy.core.Global.projections }

`core.Global.projections(net_id=0, post=None, pre=None, target=None, suppress_error=False)`

Returns a list of all declared populations. By default, the method returns all connections which were defined.
By setting *one* of the arguments, post, pre and target one can select a subset accordingly.

## Parameters

| Name             | Type                     | Description                                                                                                                                      | Default   |
|------------------|--------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `post`           | ANNarchy.core.Population | all returned projections should have this population as post.                                                                                    | `None`    |
| `pre`            | ANNarchy.core.Population | all returned projections should have this population as pre.                                                                                     | `None`    |
| `target`         | str                      | all returned projections should have this target.                                                                                                | `None`    |
| `suppress_error` | bool                     | by default, ANNarchy throws an error if the list of assigned projections is empty. If this flag is set to True, the error message is suppressed. | `False`   |

## Returns

| Type                             | Description                                                                                 |
|----------------------------------|---------------------------------------------------------------------------------------------|
| list\[ANNarchy.core.Projection\] | A list of all assigned projections in this network, or a subset according to the arguments. |